name: Code coverage
# This Workflow compute test code coverage and send the result to covecov

# TRIGGERED BY
# - push-master-ci.yml
# - push-rc-ci.yml

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - release-candidate
  workflow_call:

env:
  ext-dir: $GITHUB_WORKSPACE/external/install/

jobs:
  coverage:
    uses: ./.github/workflows/build-matrix.yml
    with:
      windows: "false"
      macos: "false"
      build-release: "false"
      build-debug: "true"
      coverage: "true"
      qt6: "false"
